window.ZIYUAN={"meta":{"title":"字園","levels":1,"perLevel":40,"total":40,"published":"github-pages-seed"},"seedMems":{"的":[{"text":"A white ladle scooping possession.","adult":false,"votes":12}]},"chars":[
{"i":1,"z":"的","lv":1,"freq":6538132,"stk":8,"zy":"ㄉㄓ˙","py":"de","rd":[{"zy":"ㄉㄓ˙","py":"de","tag":"default"}],"en":"possessive particle; of","tw":"","w":[{"w":"真的","zy":"ㄓㄣ ˙ㄉㄓ","en":"really","cn":null,"tw":false}],"lk":[],"tag":[],"stone":{"job":"particle","habitat":["螢幕","契約"],"color":"ink","register":1,"hook":"Possession glue. Almost every sentence leans on it.","weather":"before lunch","pair":"得/地","frozen":true}},
{"i":2,"z":"是","lv":1,"freq":3200626,"stk":9,"zy":"ㄕˋ","py":"shì","rd":[{"zy":"ㄕˋ","py":"shì","tag":"default"}],"en":"to be","tw":"","w":[{"w":"是不是","zy":"","en":"is it so","cn":null,"tw":false}],"lk":[],"tag":[],"stone":{"job":"verb","habitat":["對話"],"color":"ink","register":1,"hook":"The copula.","weather":"before lunch","pair":"非","frozen":true}},
{"i":3,"z":"不","lv":1,"freq":2831612,"stk":4,"zy":"ㄅㄨˋ","py":"bù","rd":[{"zy":"ㄅㄨˋ","py":"bù","tag":"default"}],"en":"not","tw":"","w":[],"lk":[],"tag":[],"stone":{"job":"adverb","habitat":["到處"],"color":"ink","register":1,"hook":"The plain no.","weather":"before lunch","pair":"沒","frozen":true}},
{"i":4,"z":"我","lv":1,"freq":2584497,"stk":7,"zy":"ㄨㄛˇ","py":"wǒ","rd":[{"zy":"ㄨㄛˇ","py":"wǒ","tag":"default"}],"en":"I; me","tw":"","w":[],"lk":[],"tag":[],"stone":{"job":"pronoun","habitat":["對話"],"color":"ink","register":1,"hook":"First person.","weather":"before lunch","pair":"","frozen":true}},
{"i":5,"z":"一","lv":1,"freq":2542556,"stk":1,"zy":"ㄧ","py":"yī","rd":[{"zy":"ㄧ","py":"yī","tag":"default"}],"en":"one","tw":"","w":[],"lk":[],"tag":[],"stone":{"job":"number","habitat":["菜單"],"color":"ink","register":1,"hook":"One, and the start of every measure phrase.","weather":"before lunch","pair":"","frozen":true}},
{"i":6,"z":"資","lv":1,"freq":1115608,"stk":13,"zy":"ㄗ","py":"zī","rd":[{"zy":"ㄗ","py":"zī","tag":"default"}],"en":"resources; capital","tw":"","w":[{"w":"資訊","zy":"ㄗ ㄒㄩㄨˋ","en":"information","cn":"信息","tw":true}],"lk":[],"tag":[],"stone":{"job":"noun","habitat":["資訊圈"],"color":"gold","register":2,"hook":"#13 on this net because 資訊 sat at the centre of 90s Taiwan boards.","weather":"before lunch","pair":"","frozen":true}},
{"i":7,"z":"這","lv":1,"freq":986130,"stk":11,"zy":"ㄓㄞˋ","py":"zhè","rd":[{"zy":"ㄓㄞˋ","py":"zhè","tag":"default"}],"en":"this","tw":"這裡, not 這兒.","w":[{"w":"這裡","zy":"ㄓㄞˋ ㄌㄧˇ","en":"here","cn":"這兒","tw":true}],"lk":[],"tag":[],"stone":{"job":"pronoun","habitat":["對話"],"color":"ink","register":1,"hook":"This. 這裡, not 這兒.","weather":"before lunch","pair":"那","frozen":true}},
{"i":8,"z":"台","lv":1,"freq":414094,"stk":5,"zy":"ㄊㄞˊ","py":"tái","rd":[{"zy":"ㄊㄞˊ","py":"tái","tag":"default"}],"en":"platform; Taiwan","tw":"Informal 台 beats official 臺.","w":[{"w":"台灣","zy":"ㄊㄞˊ ㄨㄢ","en":"Taiwan","cn":null,"tw":true}],"lk":["臺"],"tag":[],"stone":{"job":"noun","habitat":["店招"],"color":"gold","register":1,"hook":"Informal 台 beats official 臺 four-to-one on this corpus.","weather":"daily paper","pair":"臺","frozen":true}},
{"i":209,"z":"裡","lv":1,"freq":183675,"stk":13,"zy":"ㄌㄧˇ","py":"lǐ","rd":[{"zy":"ㄌㄧˇ","py":"lǐ","tag":"default"}],"en":"inside","tw":"Taiwan standard 裡.","w":[{"w":"哪裡","zy":"ㄋㄚˇ ㄌㄧˇ","en":"where","cn":"哪兒","tw":true}],"lk":[],"tag":[],"stone":{"job":"noun","habitat":["地址"],"color":"ink","register":1,"hook":"Inside. 這裡／哪裡.","weather":"daily paper","pair":"","frozen":true}},
{"i":10,"z":"臺","lv":1,"freq":109725,"stk":14,"zy":"ㄊㄞˊ","py":"tái","rd":[{"zy":"ㄊㄞˊ","py":"tái","tag":"default"}],"en":"terrace; Taiwan","tw":"Official 臺灣.","w":[{"w":"臺北","zy":"ㄊㄞˊ ㄅㄟˇ","en":"Taipei","cn":null,"tw":true}],"lk":["台"],"tag":[],"stone":{"job":"noun","habitat":["公文"],"color":"gold","register":2,"hook":"Official terrace. Street signs often write 台.","weather":"daily paper","pair":"台","frozen":true}}
]}
;